### ISSUE TITLE
单元测试集成到Gitlab CI

### ISSUE THREAD

**Issue by fayeah** [fayeah/blogs#57]
### **一、技术栈**
       vue3+jest 

### **二、结果：**

- 代码库的badge：

![image](https://user-images.githubusercontent.com/29644978/158553388-bef61dfe-3602-4bcb-b266-050683768cfb.png)

- 测试报告

![image](https://user-images.githubusercontent.com/29644978/158558228-210532cc-ff7d-472b-ad74-7fd76d50892d.png)

![image](https://user-images.githubusercontent.com/29644978/158553519-40687ce0-b538-46ca-bb0f-e264cdea4e45.png)

- 每个job都生成相应的数据，也可以下载报告

![image](https://user-images.githubusercontent.com/29644978/158554144-9ddf99c1-3d5e-43d4-9e99-bec1f2eab83f.png)

### **三、文件配置：**

- .gitlab-ci.yml

```yml
stages:
  - pages


pages:
  stage: pages
  script:
    - npm install
    - npm run test
    - mkdir .public
    - cp -r coverage/* .public
    - rm -rf public
    - mv .public public
  artifacts:
    paths:
      - public
    when: always
    reports:
      junit:
        - junit.xml
      cobertura: coverage/cobertura-coverage.xml
  tags:
    - some-runner
```

**注：**

1. stage名需为`pages`，否则无法生成page 链接。
2. `npm run test`的脚本为: `"test": "jest --config ./jest.config.js --collectCoverage --coverageDirectory=\"./coverage\" --ci --reporters=default --reporters=jest-junit --watchAll=false"`

- jest配置文件：

```JavaScript
module.exports = {
  moduleFileExtensions: [
    'js',
    'ts',
    'json',
    'vue',
    'tsx'
  ],
  transform: {
    '^.+\\.ts$': 'ts-jest',
    '^.+\\.vue$': 'vue-jest',
    '^.+\\.tsx$': 'vue-jest',
    "^.+\\.js$": "<rootDir>/node_modules/babel-jest",
  },
  modulePaths: ["src"],
  moduleDirectories: ["node_modules"],
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1'
  },
  collectCoverageFrom: [
    "src/**/*.{js,ts,tsx}",
    "!<rootDir>/node_modules/"
  ],
  coverageReporters: ["html", "text", "text-summary", "cobertura"],
}
```

### **四、Gitlab设置：**

- 测试报告的正则解析

![image](https://user-images.githubusercontent.com/29644978/158555750-9f65deeb-3764-45ca-8c06-4d87c9a1756b.png)

- badge配置：可以自己定义，例如%{default_branch} 可以改为名为"test"的分支名称，那么指定读取该分支下生成的报告或其他状态。
测试覆盖率badge

![image](https://user-images.githubusercontent.com/29644978/158557604-18ced00f-8715-40aa-8172-2f35bec6d157.png)

- pipeline状态badge

![image](https://user-images.githubusercontent.com/29644978/158557854-260b73bf-7130-4534-8150-c4694ac0c32c.png)
